-- Reconcile accumulated schema drift between migration history and the live
-- database (the result of earlier out-of-band `prisma db push` operations on
-- unrelated features: chat, agents, project, finance). This migration captures
-- exactly those differences so migration history matches the database and the
-- current schema. It is generated by `prisma migrate diff` and recorded as
-- already-applied on the canonical database (the objects already exist there).

-- DropForeignKey
ALTER TABLE "public"."ChatMessage" DROP CONSTRAINT "ChatMessage_userId_fkey";

-- DropIndex
DROP INDEX "public"."Agent_userId_key";

-- DropIndex
DROP INDEX "public"."AgentRun_agentId_sourceKey_key";

-- CreateIndex
CREATE INDEX "Project_createdById_idx" ON "public"."Project"("createdById" ASC);

-- AddForeignKey
ALTER TABLE "public"."ChatMessage" ADD CONSTRAINT "ChatMessage_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Transaction" ADD CONSTRAINT "Transaction_approvedById_fkey" FOREIGN KEY ("approvedById") REFERENCES "public"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Transaction" ADD CONSTRAINT "Transaction_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "public"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
