/**
 * The Bingkai mark: a square frame whose right side folds into a "B", around a
 * portrait. Geometry is generated by brand/build_brand.py, which measured it off the
 * source artwork in brand/bingkai-logo-source.png. Change the shapes THERE and paste
 * the output here, so this component, the favicon and the share card never drift.
 *
 * Inline rather than an <img>, so it inherits `currentColor` and needs no request.
 */
export function LogoMark({ className = "" }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 460 475"
      className={className}
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
    >
      <rect x="0" y="0" width="460" height="58" />
      <rect x="0" y="0" width="61" height="475" />
      <rect x="0" y="418" width="460" height="57" />
      <rect x="399" y="0" width="61" height="170" />
      <rect x="399" y="319" width="61" height="156" />
      <polygon points="399,170 460,170 396,235 337,235" />
      <polygon points="337,260 401,260 460,319 399,319" />
      <circle cx="230" cy="190" r="70" />
      <path d="M114,376 L114,346 A68,68 0 0 1 182,278 L274,278 A68,68 0 0 1 342,346 L342,376 Z" />
    </svg>
  );
}

/** Mark plus the tracked uppercase wordmark, as in the source artwork. */
export function Logo() {
  return (
    <span className="flex items-center gap-2.5 text-gold">
      <LogoMark className="h-6 w-auto" />
      <span className="text-[15px] font-extrabold uppercase leading-none tracking-[0.18em]">
        Bingkai
      </span>
    </span>
  );
}
